app:
  migration:
    source:
      uri: mongodb://localhost:27017/mgdb_dcen1
    targets:
      mgdb_dneas1:
        uri: mongodb://localhost:27017/mgdb_dneas1
        collections: [emailProgramData, emailTestData]
      mgdb_dnmr1:
        uri: mongodb://localhost:27017/mgdb_dnmr1
        collections: [smsShortCodeData]
        #Just for testing if target DB does not exist.
      targetDB3:
        uri: mongodb://localhost:27017/targetDB3
        collections: [c5]
